name: Preview Deploy to GitHub Pages

on:
  push:
    branches: ["preview"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-preview"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create version.json (for preview)
        run: |
          VERSION="preview-$(date -u +%Y%m%d-%H%M)"
          echo '{ "version": "'$VERSION'", "buildDate": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'", "environment": "preview" }' > version.json

      - name: Prepare deploy directory (minimal set for GitHub Pages)
        run: |
          mkdir -p deploy/media/lowscaled_images
          mkdir -p deploy/media/experimental-14mp
          cp index.html pannellum.css pannellum.js script.js version.json index.html.sig pannellum.css.sig script.js.sig favicon.ico deploy/
          cp -r additional-media deploy/
          cp -r media/lowscaled_images/* deploy/media/lowscaled_images/
          cp -r media/experimental-14mp/* deploy/media/experimental-14mp/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './deploy'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
